DROP TABLE IF EXISTS aviao_silver;

CREATE TABLE aviao_silver (
    event_id VARCHAR(50) PRIMARY KEY,
    investigation_type VARCHAR(50),
    accident_number VARCHAR(50),
    event_date DATE,
    location TEXT,
    country VARCHAR(100),
    latitude DECIMAL(10,6),
    longitude DECIMAL(10,6),
    airport_code VARCHAR(20),
    airport_name VARCHAR(200),
    injury_severity VARCHAR(50),
    aircraft_damage VARCHAR(50),
    aircraft_category VARCHAR(50),
    registration_number VARCHAR(50),
    make VARCHAR(100),
    model VARCHAR(100),
    amateur_built BOOLEAN,
    number_of_engines INT,
    engine_type VARCHAR(50),
    far_description VARCHAR(200),
    schedule VARCHAR(50),
    purpose_of_flight VARCHAR(100),
    air_carrier VARCHAR(200),
    total_fatal_injuries INT,
    total_serious_injuries INT,
    total_minor_injuries INT,
    total_uninjured INT,
    weather_condition VARCHAR(50),
    broad_phase_of_flight VARCHAR(100),
    report_status VARCHAR(50),
    publication_date DATE
);